### ISSUE TITLE
ecosense output for Fishery for each scenario?

### ISSUE THREAD

**Issue by sgaichas** [NOAA-EDAB/RpathQNM#4]
@slucey In comparing outputs across ecosense and QNM, the Fishery output for ecosense is missing.

Is the Fishery not perturbed in ecosense? or is it perturbed but not included in the rest of the ecosense output?

Example figure for decreasing phytoplankton scenario

![image](https://github.com/NOAA-EDAB/QNM/assets/8172302/eade8b2e-aa46-41bc-826f-6948fa291a7b)

**Comment by slucey** [comment]
Forgot to close this issue.  This was resolved with commit b3d2e55.

My bad.
